Dynamics for the UR5 Robot calculated versus Peter Cook

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from roboticstoolbox import DHRobot, RevoluteDH

from src.ur5_dynamics import UR5DynamicModel
from src.compare_models import compare_models

For the UR5 robot:

- Do research on its sound model;
- Check the specifications of the joints and choose compatible random efforts (forces or torques);
- Implement dynamic equations through a script (python, matlab, lua...);
- Apply efforts directly to the joints and monitor the positions of the links;
- Compare with the results obtained by applying the same efforts to the model simulated by a simulator of your choice.

In [ ]:
# Initial config
qd0 = np.zeros(6)
q0 = np.zeros(6)

# Torque input
tau = np.array([0.1, -1, -0.2, -0.2, 0.1, -0.1])

t_span = np.linspace(0, 1.0, 50)
print(len(t_span))

50


In [ ]:
print("Running own model")
ur5 = UR5DynamicModel()
sol_custom = ur5.simulate(q0, qd0, tau, t_span)

Running own model
...
Integrating dynamics using solve_ivp...
Simulating t = 0.51s

In [ ]:
print("Running Robotics Toolbox model")
ur5_rtb = DHRobot([
    RevoluteDH(d=0.089159, alpha=np.pi/2),
    RevoluteDH(a=0.425),
    RevoluteDH(a=0.39225),
    RevoluteDH(d=0.10915, alpha=np.pi/2),
    RevoluteDH(d=0.09465, alpha=-np.pi/2),
    RevoluteDH(d=0.0823)
], name="UR5")

Running Robotics Toolbox model


In [ ]:
compare_models(tau, ur5, sol_custom, ur5_rtb, t_span)

Saving plots to: /home/ivon/code/ur5_robot_dynamics_comparison/results
Configuring and simulating Robotics Toolbox model...
RTB model with parameters:
Link 1: m=3.7, r=[ 0.      -0.02561  0.00193], I=[[0.010267 0.       0.      ]
 [0.       0.010267 0.      ]
 [0.       0.       0.00666 ]]
Link 2: m=8.393, r=[0.2125  0.      0.11336], I=[[0.22689   0.        0.       ]
 [0.        0.22689   0.       ]
 [0.        0.        0.0151074]]
Link 3: m=2.33, r=[0.15   0.     0.0265], I=[[0.049443 0.       0.      ]
 [0.       0.049443 0.      ]
 [0.       0.       0.004095]]
Link 4: m=1.219, r=[ 0.      -0.0018   0.01634], I=[[0.111172 0.       0.      ]
 [0.       0.111172 0.      ]
 [0.       0.       0.21942 ]]
Link 5: m=1.219, r=[0.      0.0018  0.01634], I=[[0.111172 0.       0.      ]
 [0.       0.111172 0.      ]
 [0.       0.       0.21942 ]]
Link 6: m=0.1879, r=[ 0.        0.       -0.001159], I=[[0.017136 0.       0.      ]
 [0.       0.017136 0.      ]
 [0.       0.       0.033822]]